{
 "title": "go-runtime-stats",
 "time": { "from": "now-24h", "to": "now" },
 "panels": [
  {
   "title": "Last GC pause",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 8, "x": 0, "y": 0 },
   "format": "ns",
   "valueName": "current",
   "targets": [
    {
     "target": "metrics.prefix.gc.pause_last_ns"
    }
   ]
  },
  {
   "title": "Total GC pauses from time range",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 8, "x": 8, "y": 0 },
   "format": "ns",
   "valueName": "current",
   "targets": [
    {
     "target": "integral(consolidateBy(metrics.prefix.gc.pause_ns_total_delta, 'sum'))"
    }
   ]
  },
  {
   "title": "Time from last GC",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 8, "x": 16, "y": 0 },
   "format": "s",
   "valueName": "current",
   "targets": [
    {
     "target": "metrics.prefix.gc.time_from_last_gc_s"
    }
   ]
  },
  {
   "title": "Memory usage",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 2 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "target": "aliasByMetric(metrics.prefix.mem.heap.alloc_bytes)"
    },
    {
     "target": "aliasByMetric(metrics.prefix.mem.heap.idle_bytes)"
    },
    {
     "target": "aliasByMetric(metrics.prefix.mem.heap.sys_bytes)"
    }
   ]
  },
  {
   "title": "Gorutines",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 2 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "aliasByMetric(metrics.prefix.cpu.goroutines_number)"
    }
   ]
  },
  {
   "title": "heap objects",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "target": "metrics.prefix.mem.heap.objects_number"
    }
   ]
  },
  {
   "title": "GC pauses summ in last interval window",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "ns" }
   ],
   "targets": [
    {
     "target": "aliasByMetric(consolidateBy(derivative(metrics.prefix.gc.pause_ns_total), 'max'))"
    }
   ]
  },
  {
   "title": "Last GC Pause time",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 13 },
   "yaxes": [
    { "format": "ns" }
   ],
   "targets": [
    {
     "target": "aliasByMetric(metrics.prefix.gc.pause_last_ns)"
    }
   ]
  },
  {
   "title": "GC delta in last interval",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "alias(consolidateBy(derivative(metrics.prefix.gc.number_total), 'max'), 'GC delta')"
    }
   ]
  },
  {
   "title": "time from last GC",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 18 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "target": "aliasByMetric(consolidateBy(metrics.prefix.gc.time_from_last_gc_s, 'max'))"
    }
   ]
  }
 ]
}